repos:
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
    -   id: cargo-check
        entry: env RUSTFLAGS="-D warnings" cargo check
        args: ['--all']
    -   id: clippy
    -   id: cargo-check
        name: cargo-check --features image
        entry: env RUSTFLAGS="-D warnings" cargo check
        args: ['--all', '--features', 'image']
    -   id: clippy
        name: clippy --features image
        args: ['--features', 'image']
