[package]
name = "aparté"
version = "0.1.0"
authors = ["Paul Fariello <paul@fariello.eu>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.6"
futures = "0.1"
tokio = "0.1"
tokio-xmpp = "1.0"
xmpp-parsers = { path = "../xmpp-parsers/" }
rpassword = "3.0"
uuid = { version = "0.7", features = ["v4"]  }
minidom = "0.11"
termion = "1.5"
derive-error = "0.0.4"
bytes = "0.4"
tokio-codec = "0.1"
tokio-file-unix = "0.5"
