[package]
name = "aparté"
version = "0.1.0"
authors = ["Paul Fariello <paul@fariello.eu>"]
edition = "2018"

[features]
no-cursor-save = []

[dependencies]
log = "0.4"
simple-logging = "2.0"
futures = "0.1"
tokio = "0.1"
tokio-xmpp = "1.0"
xmpp-parsers = "0.16"
rpassword = "3.0"
uuid = { version = "0.7", features = ["v4"]  }
termion = "1.5"
derive-error = "0.0.4"
bytes = "0.4"
tokio-codec = "0.1"
tokio-file-unix = "0.5"
dirs = "2.0"
chrono = "0.4"
signal-hook = { version = "0.1", features = ["tokio-support"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
